#destination: docs

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rodrigo Leo
#tagline:          'A Jekyll theme'
description:      'Estudio economía en <a href="https://www.colmex.mx">El Colegio de México</a>.'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rodrigo Leo'
#  url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rodrigo-lp
